device: cuda
dataset:
  name: CIFAR10
model:
  type: cifar10
  name: ResNet18
  init_mode: ''
train:
  seed: 0
  precision: O0
  batch_size: 128
  epochs: 200
  optimizer: sgd
  base_lr: 0.1
  momentum: 0.9
  nesterov: True
  weight_decay: 5e-4
  output_dir: experiments/cifar10/resnet18
  val_ratio: 0.0
  use_test_as_val: True
  dataloader:
    num_workers: 2
validation:
  batch_size: 64
  dataloader:
    num_workers: 2
scheduler:
  type: multistep
  milestones: [60, 120, 160]
  lr_decay: 0.2
augmentation:
  use_random_crop: False
  use_random_horizontal_flip: False
  use_cutout: False
  random_crop:
    padding: 4
    fill: 0
    padding_mode: constant
  random_horizontal_flip:
    prob: 0.5


